#' Genes with particular expression patterns
#'
#' Based on scRNA-Seq (10x genomics generated by CeNGEN), lists genes with particular expression patterns, e.g. panneuronal etc
#'
#' List by AW. Data, see paper.
#'
#' Molecular topography of an entire nervous system
#' Seth R Taylor, Gabriel Santpere, Alexis Weinreb, Alec Barrett, Molly B. Reilly, Chuan Xu, Erdem Varol, Panos Oikonomou, Lori Glenwinkel, Rebecca McWhirter, Abigail Poff, Manasa Basavaraju, Ibnul Rafi, Eviatar Yemini, Steven J Cook, Alexander Abrams, Berta Vidal, Cyril Cros, Saeed Tavazoie, Nenad Sestan, Marc Hammarlund, Oliver Hobert, David M. Miller III
#' bioRxiv 2020.12.15.422897; doi: https://doi.org/10.1101/2020.12.15.422897
#' Now published in Cell doi: 10.1016/j.cell.2021.06.023
#'
#'
#' @format ## `gene_by_pattern`
#' A list of length 7:
#' \describe{
#'   \item{nondetected}{Note detected in scRNA-Seq of L4 hermaphrodites.}
#'   \item{nonneuronal}{detected in cells that are not neurons.}
#'   \item{ubiquitous}{likely expressed in every cell type.}
#'   \item{panneuronal}{Likely expressed in every neuron, and only in neurons.}
#'   \item{broadly_neuronal}{Expressed in many neurons.}
#'   \item{neuron_specific}{Expressed in neurons, and no other cell type.}
#'   \item{present_in_neurons}{The combination of the above lists.}
#' }
"genes_by_pattern"
